-d C:\Users\jordi\OneDrive\Documents\Projects\FPGA\SBP\SBP\impl\gwsynthesis\SBP.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\jordi\OneDrive\Documents\Projects\FPGA\SBP\SBP\src\Physical Constrains\tang_nano9k.cst
-cfg C:\Users\jordi\OneDrive\Documents\Projects\FPGA\SBP\SBP\impl\pnr\device.cfg
-sdc C:\Users\jordi\OneDrive\Documents\Projects\FPGA\SBP\SBP\src\Timming Constrains\tang_nano9k.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
